version: '3.5'

networks:
  lab_network:
    driver: bridge
    name: "lab_network"

services:

  ansible:
    image: ans
    hostname: ansible
    volumes:
      - ./:/ans
    networks:
      - lab_network
    ports:
      - "9000:22"
    command: sleep infinity

  front:
    image: my-ub
    hostname: front
    environment:
      test1: test1
    networks:
      - lab_network
    ports: 
      - "9001:22"
      - "8181:80"

  back:
    image: my-ub
    hostname: back
    environment:
      test1: test1
    networks:
      - lab_network
    ports:
      - "9002:22"
  

  db:
    image: my-ub
    hostname: db
    environment:
      test1: test1
    networks:
      - lab_network
    ports:
      - "9003:22"
      - "3306:3306"
  